coverage:
  status:
    default_rules:
      # don't send status checks that don't have flag coverage uploaded
      flag_coverage_not_uploaded_behavior: exclude

    # rules for overall project-wide coverage
    project:
      backend:
        flags:
          - backend
        target: auto
        threshold: 1%

    # rules based on the specific changes of the PR
    patch:
      backend:
        flags:
          - backend
        target: 100%
        threshold: 2%

flags:
  backend:
    paths:
      - src/classes/
